### ISSUE TITLE
Bug - Template - Doesn't activate 

### ISSUE THREAD

**Issue by Shawnoui** [Yann-Lns/RTS_Template#1]
The template does not appear as an option when creating a new project even if it has been dragged into the unreal engine files.

**Comment by Yann-Lns** [comment]
- Double check your folder repository. It should look like this : C:\Program Files\Epic Games\UE_5.0\Templates
- Make sure the repository as those 2 specific files : DefaultGame.ini and TemplateDefs.ini
![image](https://user-images.githubusercontent.com/56153568/167673611-eee1e576-0bc6-4c41-aeb2-42fb7a64523b.png)

If everything is in order it should appear with no icon as "Real Time Strategy" in the selection choice.
![image](https://user-images.githubusercontent.com/56153568/167673988-b6bf79c2-d4ee-4e9b-87c8-cd90e2592c6d.png)

**Comment by Yann-Lns** [comment]
> The template does not appear as an option when creating a new project even if it has been dragged into the unreal engine files.

In which state is your problem ?

**Comment by Shawnoui** [comment]
Sorry for the wait, the template now appears, thank you.
![image](https://user-images.githubusercontent.com/98610727/168376560-def32a29-8d4b-4cef-8e9a-22b43699eca5.png)
