### ISSUE TITLE
Improvement - Landscape buff/debuff

### ISSUE THREAD

**Issue by williamwisxs** [Yann-Lns/RTS_Template#5]
Trigger zones that buff or debuff units inside (forest, swamp, building that grants cover...)

**Comment by Yann-Lns** [comment]
Hello, could you clarify which buff or debuff you expect from this feature. All the details are necessary.

**Comment by williamwisxs** [comment]
Hi, I expect theses zones to modify attack speed and movement speed. A chance for ranged attacks to miss would be great in addition.

**Comment by Yann-Lns** [comment]
Hello,

I've added a trigger box that will buff or debuff all units with attack power, attack rate or movement speed.
![image](https://user-images.githubusercontent.com/56153568/171635199-38adbb9e-fff7-4c49-abaf-b97a751d9f42.png)

Value will be added to the initial state of the units and value can also be negative.

![image](https://user-images.githubusercontent.com/56153568/171635378-fbf95346-63d8-409c-990c-6554bd269c3f.png)

Please tell me if you find any problem with this feature in a new issues.
