### ISSUE TITLE
Improvement - Cover

### ISSUE THREAD

**Issue by Shawnoui** [Yann-Lns/RTS_Template#9]
A sizable collider that can apply a modifiable multiplier to the units' stats.

Example:
When a unit enters the collider with 100HP and that the collider is set to multiply the health variable by 1.25, the unit's health increases to 125.  When it leaves the collider it's health returns to 100 (if it didn't receive damage during its stay in the collider of course).

**Comment by Yann-Lns** [comment]
Hello,
Alright, I'll be implementing this mechanic in the next patch easier this afternoon or tomorrow.

**Comment by Yann-Lns** [comment]
I've uploaded an update with the mechanics you described.

When an unit is inside the trigger the following effect apply:

- Health x Modifier = New Health

When leaving the following effect apply :

- New Health X modifier = Health

I'll be closing this issues shortly after a few day.
